analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_local_variable: error
    invalid_assignment: error
    assignment_to_const: error
    assignment_to_final: error
    missing_return: error
    not_enough_required_arguments: error
    undefined_function: error
    undefined_method: error
    undefined_class: error
    missing_js_lib_annotation: ignore
  exclude:
    - lib/**.g.dart

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - comment_references
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_bool_in_asserts
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - sort_unnamed_constructors_first
    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_getters_setters
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_statements
    #- unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - prefer_expression_function_bodies
    - avoid_positional_boolean_parameters
    - always_put_control_body_on_new_line
    #- prefer_asserts_in_initializer_lists
    - unnecessary_brace_in_string_interps
    - prefer_collection_literals
    #- use_setters_to_change_properties
    #- avoid_setters_without_getters
    - cascade_invocations
    - omit_local_variable_types
    #- avoid_catches_without_on_clauses
    #- avoid_returning_null
    - unnecessary_lambdas

    #- prefer_interpolation_to_compose_strings
    #- avoid_function_literals_in_foreach_calls
    #- public_member_api_docs
    #- sort_constructors_first
    #- always_specify_types
    #- avoid_annotating_with_dynamic
    #- avoid_as
    #- avoid_catching_errors
    #- avoid_classes_with_only_static_members
    #- avoid_returning_this
    #- unawaited_futures
    #- one_member_abstracts
    #- avoid_types_on_closure_parameters
    #- close_sinks # https://github.com/dart-lang/linter/issues/268
    #- constant_identifier_names

